CREATE TABLE IF NOT EXISTS PRODUCTOS(
    ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL, 
    CANTIDAD INT NOT NULL
);